# Generated by Django 5.2.14 on 2026-05-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height_decimeters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight_hectograms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
